{
 "title": "Conso Elec",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Tarif actuel",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "dateFormat": "YYYY-MM-DD HH:mm:ss",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "PTEC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "String Threshold"
    }
   ]
  },
  {
   "title": "HC - JB",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJB",
     "query": "SELECT \"value\" FROM \"BBRHCJB\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HC - JW",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJW",
     "query": "SELECT \"value\" FROM \"BBRHCJW\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HC - JR",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJR",
     "query": "SELECT \"value\" FROM \"BBRHCJR\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAPP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "format": "voltamp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PAPP",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IINST1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IINST1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IINST2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IINST2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IINST3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 21, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IINST3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HP - JB",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 2 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJB",
     "query": "SELECT \"value\" FROM \"BBRHPJB\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HP - JW",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 2 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJW",
     "query": "SELECT \"value\" FROM \"BBRHPJW\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HP - JR",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 2 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJR",
     "query": "SELECT \"value\" FROM \"BBRHPJR\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PAPP",
   "type": "graph",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PAPP",
     "query": "SELECT value FROM \"PAPP\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IINST1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IINST1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ISOUSC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IINST2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IINST2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ISOUSC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "IINST3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "IINST3",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ISOUSC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Conso - Period",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "HCJB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJB",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HPJB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJB",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HCJW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJW",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HPJW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJW",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HCJR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJR",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "HPJR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJR",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Costs - Period",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "HCJB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJB",
     "query": "SELECT distinct(\"value\")  / 1000 * 0.1104 FROM \"BBRHCJB\" WHERE $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 0.1104" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "HPJB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJB",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 0.1329" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "HCJW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJW",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 0.1255" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "HPJW",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJW",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 0.1558" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "HCJR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHCJR",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 0.1323" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "HPJR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "BBRHPJR",
     "query": "SELECT value FROM \"BBRHPJB\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000 * 0.5413" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}